
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package gramatica;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int poligono = 19;
  public static final int circulo = 16;
  public static final int coma = 2;
  public static final int numero = 20;
  public static final int animar = 13;
  public static final int umas = 23;
  public static final int por = 5;
  public static final int parentesis_b = 8;
  public static final int linea = 10;
  public static final int parentesis_a = 7;
  public static final int menos = 4;
  public static final int div = 6;
  public static final int EOF = 0;
  public static final int curva = 11;
  public static final int cuadrado = 17;
  public static final int error = 1;
  public static final int color = 9;
  public static final int rectangulo = 18;
  public static final int graficar = 12;
  public static final int anterior = 15;
  public static final int umenos = 22;
  public static final int residuo = 21;
  public static final int mas = 3;
  public static final int objeto = 14;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "coma",
  "mas",
  "menos",
  "por",
  "div",
  "parentesis_a",
  "parentesis_b",
  "color",
  "linea",
  "curva",
  "graficar",
  "animar",
  "objeto",
  "anterior",
  "circulo",
  "cuadrado",
  "rectangulo",
  "poligono",
  "numero",
  "residuo",
  "umenos",
  "umas"
  };
}

